# Generated by Django 5.1.3 on 2024-12-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightsource',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='project',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='project',
        ),
        migrations.DeleteModel(
            name='Heliostat',
        ),
        migrations.DeleteModel(
            name='Lightsource',
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
