# Generated by Django 5.1.4 on 2025-01-14 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=500)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "owner")},
            },
        ),
        migrations.CreateModel(
            name="Lightsource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_rays", models.IntegerField(default=100)),
                ("lightsource_type", models.CharField(default="sun", max_length=300)),
                (
                    "distribution_type",
                    models.CharField(default="normal", max_length=300),
                ),
                ("mean", models.FloatField(default=0)),
                ("covariance", models.FloatField(default=4.3681e-06)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lightsources",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Heliostat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("position_z", models.FloatField(default=0)),
                ("aimpoint_x", models.FloatField(default=0)),
                ("aimpoint_y", models.FloatField(default=50)),
                ("aimpoint_z", models.FloatField(default=0)),
                ("number_of_facets", models.IntegerField(default=4)),
                ("kinematic_type", models.CharField(default="ideal", max_length=300)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heliostats",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("position_z", models.FloatField(default=0)),
                ("normal_x", models.FloatField(default=0)),
                ("normal_y", models.FloatField(default=1)),
                ("normal_z", models.FloatField(default=0)),
                ("rotation_y", models.FloatField(default=0)),
                ("curvature_e", models.FloatField(blank=True, default=None, null=True)),
                ("curvature_u", models.FloatField(blank=True, default=None, null=True)),
                ("plane_e", models.FloatField(default=8.629666667)),
                ("plane_u", models.FloatField(default=7.0)),
                ("resolution_e", models.IntegerField(default=256)),
                ("resolution_u", models.IntegerField(default=256)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shadows", models.BooleanField(default=True)),
                ("fog", models.BooleanField(default=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="project_management.project",
                    ),
                ),
            ],
        ),
    ]
