# Generated by Django 4.2.17 on 2025-01-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_project_preview_alter_project_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='projectPreviews/logo_canvas.jpg', upload_to='projectPreviews'),
        ),
    ]
