# Generated by Django 4.2.17 on 2025-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_project_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='media/projectPreviews/logo_canvas.jpg', upload_to='media/projectPreviews'),
        ),
    ]
