# Generated by Django 4.2.17 on 2025-01-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_alter_project_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorite',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='projectPreviews/logo_canvas.jpg', upload_to='projectPreviews'),
        ),
    ]
