# Generated by Django 4.2.17 on 2025-01-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_project_favorite_alter_project_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='favorite',
            field=models.CharField(default='false', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='project_previews/logo_canvas.jpg', upload_to='project_previews/'),
        ),
    ]
