# Generated by Django 4.2.17 on 2025-01-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_alter_project_favorite_alter_project_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='project_previews/emptyEditor.png', upload_to='project_previews/'),
        ),
    ]
