# Generated by Django 5.1.4 on 2025-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0008_lightsource_name_receiver_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiver",
            name="position_y",
            field=models.FloatField(default=50),
        ),
    ]
