# Generated by Django 4.2.17 on 2025-01-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_alter_project_preview'),
        ('project_management', '0009_alter_receiver_position_y'),
    ]

    operations = [
    ]
