# Generated by Django 5.1.4 on 2025-01-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0010_merge_20250124_1103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiver",
            name="curvature_e",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="curvature_u",
            field=models.FloatField(default=0),
        ),
    ]
