# Generated by Django 5.1.3 on 2025-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_merge_20250201_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heliostat',
            name='name',
            field=models.CharField(blank=True, default='Heliostat', max_length=200),
        ),
        migrations.AlterField(
            model_name='lightsource',
            name='name',
            field=models.CharField(blank=True, default='Light source', max_length=200),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='name',
            field=models.CharField(blank=True, default='Receiver', max_length=200),
        ),
    ]
