# Generated by Django 5.1.3 on 2025-02-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_merge_20250128_0951'),
        ('project_management', '0012_merge_20250131_0855'),
    ]

    operations = [
    ]
