# Generated by Django 5.1.4 on 2025-02-02 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_management",
            "0013_alter_heliostat_name_alter_lightsource_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_shared",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_edited",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="SharedProject",
        ),
    ]
