# Generated by Django 5.1.3 on 2025-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0015_merge_20250203_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.ImageField(upload_to='project_previews/'),
        ),
    ]
