# Generated by Django 5.1.4 on 2025-02-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0012_merge_20250128_0951"),
        ("project_management", "0012_merge_20250131_0855"),
        ("project_management", "0015_alter_project_last_shared"),
    ]

    operations = []
